[package]
authors = ["Alex Johnson <alex_johnson3@yahoo.com>"]
name = "nbody"
version = "0.1.0"

[dependencies]
itertools = "*"
num = "*"
piston_window = "*"
rand = "*"
rayon = "*"
time = "*"

[profile.release]
opt-level = 3